services:
  mdtopic:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    container_name: mdtopic
    # 资源限制
    mem_limit: 2g
    cpus: 1
    # 共享内存配置
    shm_size: '1gb'
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"